export const ENV_VARS = {
  PORT: 'PORT',
  MONGO_DB_USER: 'MONGO_DB_USER',
  MONGO_DB_PASSWORD: 'MONGO_DB_PASSWORD',
  MONGO_DB_HOST: 'MONGO_DB_HOST',
  MONGO_DB_DATABASE: 'MONGO_DB_DATABASE',
};

export const SMTP = {
  SMTP_HOST: 'SMTP_HOST',
  SMTP_PORT: 'SMTP_PORT',
  SMTP_USER: 'SMTP_USER',
  SMTP_PASSWORD: 'SMTP_PASSWORD',
  SMTP_FROM: 'SMTP_FROM',
};
